Even more sync repos improvements

diff --git a/jd/libexec/jd-git-sync b/jd/libexec/jd-git-sync
--- a/jd/libexec/jd-git-sync
+++ b/jd/libexec/jd-git-sync
@@ -21,42 +21,41 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-git fetch $quiet --all -Pp
-
-if [ -n "$(git status --porcelain | egrep -v '^\?\? ')" ]; then
-  echo "ERROR: You have a dirty working copy. This command would remove any files not already checked in" >&2
-  exit 1
-fi
+git fetch $quiet --progress --all -Pp
 
 defaultbranch="$(git config init.defaultbranch)"
 defaultbranch="${defaultbranch:-main}"
 currentbranch="$(git rev-parse --abbrev-ref HEAD)"
 
-confirm() {
-  while true; do
-    read -n 1 -r -p "${1:-Are you sure?} [y/N] " response
-    echo
-    case "$response" in
-        [yY])
-            return 0
-            ;;
-        [nN])
-            return 1
-            ;;
-        *)
-          echo "Choose 'n' or 'y'";;
-    esac
-  done
-}
-
 set -e
 
-git for-each-ref --format '%(refname:short):%(upstream:short)' 'refs/heads' | egrep -v ':$' | while IFS=: read local remote; do
-  if [ -z "$quiet" ]; then
-    echo "Syncing ${local} with ${remote}"
+message() {
+  if [[ -z "$quiet" ]]; then
+    echo $@
   fi
-  git checkout -q "$local"
-  git merge $quiet --ff-only "$remote"
-done
+}
 
-git checkout -q "$currentbranch"
+git for-each-ref --format '%(refname:short):%(upstream:short)' 'refs/heads' | egrep -v ':$' | while IFS=: read local remote; do
+  message "Syncing ${local} with ${remote}"
+
+  fullbranch="refs/heads/${local}"
+  fullremote="refs/remotes/${remote}"
+  branchsha="$(git rev-parse -q $fullbranch)"
+  remotesha="$(git rev-parse -q $fullremote)"
+
+  if [[ -z "$remotesha" || "$branchsha" = "$remotesha" ]]; then
+    message "${local} is up to date"
+  elif (git merge-base --is-ancestor "$branchsha" "$remotesha" > /dev/null) ; then
+    if [[ "$local" == "$currentbranch" ]]; then
+      if [ -n "$(git status --porcelain | egrep -v '^\?\? ')" ]; then
+        echo "ERROR: ${local} has files that are not checked in" >&2
+      else
+        git merge $quiet --ff-only "$remote"
+      fi
+    else
+      git update-ref "$fullbranch" "$fullremote"
+    fi
+  else
+    echo "WARN: ${local} has unpushed commits"
+  fi
+done
